[alembic]
script_location = alembic
file_template = %%(rev)s_%%(slug)s
sqlalchemy.url = postgresql+asyncpg://therados:therados_dev_password@localhost:5432/therados_db

[post_write_hooks]

[logging]
default_level = INFO
